#!/usr/bin/env sh
set -e

path_file_unicodeblocks="/usr/share/unicode/Blocks.txt"

[ -r "$path_file_unicodeblocks" ] || {
  echo "$(basename "$0"): This script requires the Blocks.txt file from the package unicode-character-database"
  exit 1
}

file_unicodeblocks="$(<"$path_file_unicodeblocks")"

line_number_begin_blocks="$(grep "^0000..007F" --line-number <<< $file_unicodeblocks | cut -d ":" -f 1)"
line_number_end_blocks="$(grep "^100000..10FFFF" --line-number <<< $file_unicodeblocks | cut -d ":" -f 1)"

unicodeblocks="$(
  printf "%s" "$file_unicodeblocks" | head -n "$line_number_end_blocks" | tail -n"+$line_number_begin_blocks"
)"

echo "$unicodeblocks" | sed -e 's/^/[ /g' | sed -e 's/; / ] - [ /g' | sed -e 's/$/ ]/g'
