#!/usr/bin/env sh
# set -e

# https://stackoverflow.com/questions/5517500/generating-hex-numbers-of-a-certain-range#--stacks-s-tooltip-al8e8hxb

path_file_unicodedata="/usr/share/unicode/UnicodeData.txt"

[ -r "$path_file_unicodedata" ] || { echo "$(basename "$0"): This script requires the UnicodeData.txt file from the package unicode-character-database"; exit 1; }

codes="$(cut -d ";" -f "1" <"$path_file_unicodedata")"

begin=$1
end=$2

file_range_from=""
file_range_to=""

# format of the larger number
# if test "${#from}" -gt "${#to}"; then
#   format="%0${#from}X\n"
# else
#   format="%0${#to}X\n"
# fi

format="%0${#end}X\n"
formatted_hex_begin="$(printf '%d' "0x$begin")"
formatted_hex_end="$(printf '%d' "0x$end")"
