#!/usr/bin/env sh
set -e

win="$(xdotool getwindowfocus)"

output="$(ucmenu -m "dmenu -p '%P'" -n "dmenu -p '%P'" -r "dmenu -p '%P'")"

xdotool windowactivate "$win"

tmp="$output"
while [ -n "$tmp" ]; do
  rest="${tmp#?}" first="${tmp%"$rest"}"
  xdotool key "U$(echo -n "$first" | iconv -f "utf8" -t "utf32le" | hexdump -e '"%04X\n"')"
  tmp="$rest"
done
