#!/usr/bin/env sh
set -eu

output="$(ucmenu)"

if [ "$output" ]; then
  if [ "${DISPLAY:-""}" ] && [ -z "${WAYLAND_DISPLAY:-""}" ] && [ "$(command -v "xclip")" ]; then
    echo "$output" | xclip -sel "clipboard"
    exit
  fi

  if [ "${WAYLAND_DISPLAY:-""}" ] && [ "$(command -v "wl-copy")" ]; then
    echo "$output" | wl-copy
    exit
  fi

  if [ "$(command -v "pbcopy")" ]; then
    echo "$output" | pbcopy
    exit
  fi

  exit "1"
fi
